### ISSUE TITLE
is authentication middleware supported?

### ISSUE THREAD

**Issue by webdesq** [davesag/swagger-routes-express#11]
Hi Dave, I'm trying to use your swagger-routes-express lib to generate API from an OpenAPI v3.0.1 spec. This spec defines security section with a simple apiKey to limit access to certain API calls to those who can provide correct apiKey header.

As far as I could see in the source code, the current version does not support generation of routes that have a middle parameter set to authorize requests. Is there another way to support API authentication? Or is in one the roadmap for next version? Can I help to implement this?

Regards,
Bart Pype

**Comment by davesag** [comment]
Hi Bart,

Currently this is only tested against the Swagger 2 spec. I plan on working on a v3 version however as there's some features of v3 I really like.

You can already add auth handlers.  See https://github.com/davesag/swagger-routes-express#adding-security-handlers

Cheers

Dave

**Comment by webdesq** [comment]
I tried to use 'global' security definition. In the OpenAPI v3 specification you can define a default security setting on root level. This applies to all routes, but can be overriden if a route has it's own security specifition. When a route has a security tset to empty array you can access that route without any authorisation middleware. As far as I could tell, this behaviour is not currently supported. Perhaps this is also v3 specific?

**Comment by davesag** [comment]
@webdesq Hi Bart, I have created issue #14 to address this as part of an overall update to support version 3
