### ISSUE TITLE
Is this package maintained

### ISSUE THREAD

**Issue by magnuspaaske** [davesag/swagger-routes-express#174]
I was wondering if this package is maintained. There are a bunch of open PRs (including my own, https://github.com/davesag/swagger-routes-express/pull/153). Would be great to either have the PR be rejected or the repo updated.

**Comment by davesag** [comment]
Hi @magnuspaaske sorry yes I've been distracted by real work for a while so have not had a chance to check your PR. I am back now and will do that shortly (this week)
