### ISSUE TITLE
Error when configuring absolute server url at openapi specification

### ISSUE THREAD

**Issue by axcosta** [davesag/swagger-routes-express#274]
If server url is configured with scheme and host (and port), instead of simple `/api/v1` (as in [example given](https://github.com/davesag/swagger-routes-express#openapi-version-3-example)):

```(yaml)
servers:
  - url: http://localhost:4001/api/v1
```

Express API becomes inaccessible when executing (for example) `curl -X GET "http://localhost:4001/api/v1/" -H  "accept: application/json"`. thus returning:

```(html)
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/v1/</pre>
</body>
</html> 
```

**Comment by davesag** [comment]
Thanks @axcosta - if you take a look at the README you'll see the following note under [OpenAPI version 3](https://github.com/davesag/swagger-routes-express#openapi-version-3)

> The OpenAPI V3 format allows you to define both a default `servers` array, and `path` specific `servers` arrays. The `url` fields in those arrays are parsed, ignoring any absolute URLS (as they are deemed to refer to controllers external to this API Server).

I recommend you don't use absolute URLs in the `servers` array.
