### ISSUE TITLE
Return type of summarise is wrong

### ISSUE THREAD

**Issue by robrop** [davesag/swagger-routes-express#315]
Currently the summarise function has the type void
https://github.com/davesag/swagger-routes-express/blob/8d56ddd3fdb4314a240d69ef8807dd01907989eb/index.d.ts#L38

### IntelliJ Code Analysis:
Warning: Void function return value is used

**Comment by davesag** [comment]
Thanks for reporting this @robrop 

I've fixed this in PR #317 

Would you mind verifying that the change I've made is correct, as I don't generally work in TypeScript

If you are happy with that I'll merge the PR and release a new version.

Cheers Dave

**Comment by davesag** [comment]
Okay released Version 3.3.1 with fixed types.

**Comment by robrop** [comment]
Looks good. Thanks for fixing!
