### ISSUE TITLE
Problem with security blocks for paths in swagger 2 definition

### ISSUE THREAD

**Issue by marcorinck** [davesag/swagger-routes-express#67]
I have a swagger api definition with no global security block but security blocks for a few paths and wanted to connect my security middleware to the routes created by swagger-routes-express. Note: the routes are working just fine and are succesfully connected to my operations.

The problem is, that the parsed security for paths with defined security is resolved to an empty string. For paths without security its undefined which is correct I assume. Because of the empty security string on the path, swagger-routes-express can't connect the security middleware from the options to the path. 

Here are the relevant parts of my yaml:

````yaml
/companies:
    get:
      tags:
        - Backoffice
      summary: returns array of surveys according to search params
      operationId: getCompanies
      security:
        - Bearer: []
      responses:
        200:
          description: "OK"
          schema:
            type: array
            items:
              $ref: '#/definitions/Company'
        400:
          description: "Bad request"
          schema:
            $ref: '#/responses/BadRequest'

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

````

Here is the parsed JSON definition of the path (done by YAMLJS)

````json
{
  "/companies": {
    "get": {
      "tags": [
        "Backoffice"
      ],
      "operationId": "getCompanies",
      "security": [
        {
          "Bearer": []
        }
      ],
      "responses": {
        // ... snipped
      }
    }
  },
}
````

The problematic code is in [normaliseSecurity.js](https://github.com/davesag/swagger-routes-express/blob/develop/src/normalise/v2/normaliseSecurity.js). The normaliseSecurity function gets this array as its security parameter for the above mentioned path:

````json
[
  {
    "Bearer": []
  }
]
````

I don't really know what you are trying to do in this function, but with the above definition, it returns just an empty string. 

Are my definitions wrong? Or is this a bug?

**Comment by davesag** [comment]
Hi @marcorinck I'll look into this and get back to you.

**Comment by davesag** [comment]
Hi @marcorinck 

So the way this works is in your security block you define some scopes under the security strategy. I appreciate that the Swagger API allows for there to be no scopes, ie

```yml
security:
  - Bearer: []
```

but `swagger-routes-express` then doesn't know how to connect that to a security middleware.

I can certainly look at supporting this but in the meantime try just adding a scope such as this

```yml
security:
  - Bearer:
    - basic
```

and then add the following `security` block to your call to `connector`

```js
const connect = connector(api, apiDefinition, {
  security: { basic: yourAuthMiddleware }
})
```

I will create a new ticket to update the library to allow for the situation where there are no scopes, so:

```yml
security:
  - Bearer: []
```

and

```js
const connect = connector(api, apiDefinition, {
  security: yourAuthMiddleware
})
```

I'll also need to have a look at what impact this has on version Open API version 3 docs.


I hope the workaround above helps in the short term.  Thanks for raising this issue.

**Comment by marcorinck** [comment]
Thank for the quick response! 

Yes the workaround indeed works. I will leave it like that for now and will close the issue.

PS: thanks for this awesome library!
