### ISSUE TITLE
Typescript definition file

### ISSUE THREAD

**Issue by marcorinck** [davesag/swagger-routes-express#69]
I'm using your library in a typescript project and as Typescript was complaining that type definitions were missing for your package I had to write my own definition for it. 

Maybe you want to publish this as part of the DefinitelyTyped project like described [here](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) so others don't have to do the same.

I'm not sure if I have gotten everything correctly, but its working in my project. I'm not using all options though, so maybe I've got something wrong. And I'm still unsure about the correct naming of the variables/interfaces, feel free to change them.

````typescript
// Type definitions for [swagger-routes-express] [3.0.5]
declare module 'swagger-routes-express' {
	import {Handler, Router} from "express";

	interface SwaggerOperations {
		[key: string]: Handler;
	}

	interface SwaggerRoutesOptions {
		security?: {
			[key: string]: Handler;
		};

		middleware?: {
			[key: string]: Handler;
		};

		onCreateRoute?: (method: string, descriptor: any[]) => void;

		apiSeparator?: string;
		notImplemented?: Handler;
		notFound?: Handler;
		rootTag?: string;
		variables?: object;
	}

	export function connector(api: SwaggerOperations, apiDefinition: object, options?: SwaggerRoutesOptions): (router: Router) => void;
}

````

**Comment by davesag** [comment]
Hi @marcorinck I'm not a typescript coder myself and so don't really know much about it or how the typing system works.  Feel free to publish your own however and raise a PR with instructions for using it in the `README`.

**Comment by davesag** [comment]
It's important to note that the `connector` function returns a function which modifies the `app`.  I'm not sure how to reflect this in TypeScript however.

I have tweaked the definition you supplied above as follows:

```
declare module 'swagger-routes-express' {
    import {Handler, Router} from "express";

    interface Controllers {
        [key: string]: Handler;
    }

    interface Options {
        security?: {
            [key: string]: Handler;
        };

        middleware?: {
            [key: string]: Handler;
        };

        onCreateRoute?: (method: string, descriptor: any[]) => void;

        apiSeparator?: string;
        notImplemented?: Handler;
        notFound?: Handler;
        rootTag?: string;
        variables?: object;
    }

    export function connector(api: Controllers, apiDefinition: object, options?: Options): (router: Router) => void;
}
```

**Comment by davesag** [comment]
On a personal note I find Typescript to be mostly pointless and annoying.

**Comment by marcorinck** [comment]
The return type of the connector function is currently the same type as the original express function as I thought that its just the router. 

What do you mean that it modifies the app? Does it add new properties or methods? I can't find any mention of that in your readme and if not, then the type is sufficient. If it just modifies it internally and the public API doesn't change, the current type is also sufficient.

I understand that you are not a typescript fan and I don't want to discuss that here. Problem is, if you are not willing to officially support the typings in future versions, its not of much use to include it because of future changes. Maybe include a link with an example gist in your Readme then? 

I don't want to publish typings on defintelytyped either, as I can't commit to maintain them for future versions and I don't want to publish typings that are superseded by the next version and no one is maintaining them.

**Comment by davesag** [comment]
Hi @marcorinck 

The `connector` function returns a function which takes the `app` as an argument, and runs the various `app.post`, `app.get` etc methods.  It's not altering the `app` itself.

I'm happy to accept a PR that includes a `ts` definition as part of this module if that suits you better, along with a small update to the readme that explains how to use it.

The api of this module is unlikely to change much in the foreseeable future as it's now quite stable.  Any significant changes will involve a major version number bump.

**Comment by okbrown** [comment]
I found this whole conversation anticlimactic. So no typings then?

**Comment by davesag** [comment]
> I found this whole conversation anticlimactic. So no typings? ... custom is it then.

Feel free to raise a PR if you want to.

**Comment by rodrigofeijao** [comment]
I've created a PR to add these, let me know if there's anything else major missing at it.
