### ISSUE TITLE
Ambiguous instructions

### ISSUE THREAD

**Issue by MagnusBrzenk** [davesag/swagger-routes-express#74]
Your readme page says:

```
Supply a security option as follows

const options = {
  security: {
    'read,write': readWriteAuthMiddlewareFunction,
    admin: adminAuthMiddlewareFunction
  }
}

```
... but doesn't say **where**.

**Comment by davesag** [comment]
These options are passing into the `connector` function as an optional third param

```js
const connect = connector(api, apiDefinition, options)
```

Sorry that this is not clear. I will update the README to make that clearer.

Cheers and thanks for your feedback.

**Comment by davesag** [comment]
@MagnusBrzenk please take a look at the newly revised readme in the `develop` branch and let me know if that makes more sense / is clearer.
